import pickle

WORDS = pickle.load(open("Gwords/gwords.pickle","rb"))
PHRASES = {
    "O FLQBX BGX IQQND O DGQSPH GCYX PONXH BQ LXCH. BGCB'D CPFCAD IXXU JA LXCDQU RQL FLOBOUZ. TXQTPX FQU'B FLOBX BGX IQQND O FCUB. DQ O GCYX BQ HQ OB RQL JADXPR. - W.D.PXFOD": {"A":"Y"},
    "M DBQZ RT GNTYEMUDKMND DEUD XOXKTBLX EUDXN RX. EX NUMZ M AUN FXMLC KMZMYWQBWN XOXKTBLX EUNL'D RXD RX TXD -KBZLXT ZULCXKIMXQZ":{"O":"V"},
    "TXBR ROQX AB AVXQ BVA. HY GBV KHDAQX AB ABB IVNO UFZHNQ GBV IUG RFHX VL IUTXHE BOAQM LQBLKQ'D IHDAUTPD. - UXX KUXFQMD":{"T":"K"},
    "PAO XN XNVZ MKPMOZ LMCD JN JAD XNNL PADW JAD XNNLQDKK LTWVZ? TJ'S AMLXKO DYDL UNL JADB.": {"X":"D"},
    "JLX WUCXV DWQ KXJ. JLX HWVX DWQ VXPUEIX DWQ TPOOWJ SEO WO JLX EOJXVOXJ. -NXFEO GHEJL" : {"W":"O"}
}
