import pickle

Gwords = pickle.load(open("Gwords/gwords.pickle","rb"))
Pwords = pickle.load(open("Gwords/pwords.pickle","rb"))
Phrases = {
    "JQV SCCVU RSUV SZ JQV HTZJ SHLTUJPCJ JQSCB HPCMSCN LTZZVZZVZ":{},
    "ANPWU KCY YH DAH WHAH DKZ KCUWNKP ODK FDA CVA RHAEHOUNCK CA MUHDQ UWH BCG CE UWNM RHAEHOU FCFHKU":{},
    "JZO XWWK BZ UVCW BMUW RZP JZOP RVUMHJ XZ UVBBWP QYVB YVFFWXA MX JZOP HMRW": {},
    "NDC LWZZCGCXVC ICNRCCX ECA FXL BPJC WE NDFN ECA GCBWCJCE NCXEWPX FXL BPJC VFMECE WN":{},
    "SQV LQMY YQTNGPFENS FN FNGQYMFQ KNNGT INYQ OGMZGL XYNWEZQZ FAET ZNQT SNF QSJNPYMOQ FAQI FN FMBQ PX INYQ NK IL FEIQ CMIQT MOMFQ":{},
    "O FLQBX BGX IQQND O DGQSPH GCYX PONXH BQ LXCH. BGCB'D CPFCAD IXXU JA LXCDQU RQL FLOBOUZ. TXQTPX FQU'B FLOBX BGX IQQND O FCUB. DQ O GCYX BQ HQ OB RQL JADXPR. - W.D.PXFOD": {"A":"Y"},
    "M DBQZ RT GNTYEMUDKMND DEUD XOXKTBLX EUDXN RX. EX NUMZ M AUN FXMLC KMZMYWQBWN XOXKTBLX EUNL'D RXD RX TXD -KBZLXT ZULCXKIMXQZ":{"O":"V"},
    "TXBR ROQX AB AVXQ BVA. HY GBV KHDAQX AB ABB IVNO UFZHNQ GBV IUG RFHX VL IUTXHE BOAQM LQBLKQ'D IHDAUTPD. - UXX KUXFQMD":{"T":"K"},
    "PAO XN XNVZ MKPMOZ LMCD JN JAD XNNL PADW JAD XNNLQDKK LTWVZ? TJ'S AMLXKO DYDL UNL JADB.": {"X":"D"},
    "JLX WUCXV DWQ KXJ. JLX HWVX DWQ VXPUEIX DWQ TPOOWJ SEO WO JLX EOJXVOXJ. -NXFEO GHEJL" : {"W":"O"},
    "NAS VHV HY WJY MA OXYJ MA MAAF? HY'M FHWNY EJZADJ HY'M XZYJDFAAF. VJIJUEJD HM NJDJ EJZADJ HY'M TKFJ. -VD. MJKMM":{"A":"O"},
    "NYEL JX WNL WNJGA SJWN TLFWNLIX WNFW ELIUNLX JG WNL XYBH FGP XJGAX WNL WBGL SJWNYBW WNL SYIPX FGP GLMLI XWYEX FW FHH LCJHQ PJURJGXYG":{"S":"W"},
    "F YKHDNFHDY NRFIA MD VKIYFJDP NKK HXVR NRD UKKJ ZXVA KG NRD DQPZO WFPJ QIJ IKN DIKXUR NRD WQJ ZXVA KG NRD DQPZO MKPH -GPQIAZFI J PKKYDTDZN": {"H","M"},
    "C QZHK GUZ CXGZQXZG BD SMVU C YZZI ICWZ C'S DX FHPZ DXZ SCIICDX DY GUZ ADQBG NDDW ZTZQ - HECE HXBHQC":{"W":"K"},
    "KA HAL BAHBSVCS LOTL JVHS BNALOSY RTDS JVHS RSH. THF RAGS LOTH JVHS JSTLOSGY RTDS JVHSXVGKY. - PSAGPS UTYOVHPLAH": {"A":"O"}
}
